version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "web/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
