version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "web/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint*"
      prettier:
        patterns:
          - "prettier*"
