version: '3'

services:
  ced-ui:
    image: ghcr.io/bradenrayhorn/ced-ui:latest
    env_file: .env
    environment:
      PUBLIC_BASE_API_URL: http://localhost:${SERVER_PORT}
      UNPROXIED_BASE_API_URL: http://ced-server:${SERVER_PORT}
      ORIGIN: http://localhost:${UI_PORT}
    ports:
      - "${UI_PORT}:${UI_PORT}"
    networks:
      - ced
  ced-server:
    image: ghcr.io/bradenrayhorn/ced-server:latest
    env_file: .env
    environment:
      HTTP_PORT: ${SERVER_PORT}
      DB_PATH: /app-data/ced.db
      ORIGIN: http://localhost:${UI_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${APP_DATA_LOCATION}:/app-data/
    networks:
      - ced

networks:
  ced:
