apiVersion: v1
kind: Service
metadata:
  name: {{ include "ced.fullname" . }}-server
  labels:
    {{- include "ced.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ced.selectorLabelsServer" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ced.fullname" . }}-ui
  labels:
    {{- include "ced.labelsUI" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ced.selectorLabelsUI" . | nindent 4 }}
---
