name: Build

on:
  workflow_call:
    inputs:
      server-tags:
        required: true
        type: string
      ui-tags:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ""

jobs:
  build_server:
    name: Build server image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: "${{ inputs.ref }}"

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Generate backend license text
        working-directory: "./server"
        run: |
          go install github.com/google/go-licenses@latest
          go-licenses report --ignore github.com/bradenrayhorn/ced --confidence_threshold 0.85 --template ./licenses.tpl --logtostderr=false ./... > ./licenses.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: 'arm64,amd64'

      - name: Login to registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Build and push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          push: true
          provenance: false
          context: "./server"
          tags: "${{ inputs.server-tags }}"
          platforms: linux/amd64,linux/arm64

  build_ui:
    name: Build ui image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Generate backend license text
        run: |
          go install github.com/google/go-licenses@latest
          (cd ./server && go-licenses report --ignore github.com/bradenrayhorn/ced --confidence_threshold 0.85 --template ./licenses.tpl --logtostderr=false ./... > ../ui/src/routes/about/server-licenses.txt)
          ls -lah ./ui/src/routes/about
          cat ./ui/src/routes/about/server-licenses.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: 'arm64,amd64'

      - name: Login to registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: check path again
        run: |
          ls -lah ./ui/src/routes/about
          cat ./ui/src/routes/about/server-licenses.txt

      - name: Build and push
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6
        with:
          push: true
          provenance: false
          context: "./ui"
          tags: "${{ inputs.ui-tags }}"
          platforms: linux/amd64,linux/arm64

