name: Apply comment

on:
  workflow_call:
    inputs:
      comment:
        required: true
        type: string
      searchKey:
        required: true
        type: string
      issueNumber:
        required: true
        type: string

jobs:
  apply-comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const desired = '${{inputs.comment}}';
            const comments = await github.paginate(github.rest.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: '${{inputs.issueNumber}}',
            });

            const comment = comments.find(c => 
              c.user.login === "github-actions[bot]" &&
              c.body.includes('${{inputs.searchKey}}')
            );

            if(!comment && desired) {
              await github.rest.issues.createComment({
                issue_number: '${{inputs.issueNumber}}',
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: desired,
              });
            } else if(comment && desired) {
              await github.rest.issues.updateComment({
                comment_id: comment.id.toString(),
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: desired,
              });
            } else if(comment && !desired) {
              await github.rest.issues.deleteComment({
                comment_id: comment.id.toString(),
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            }
