name: Undeploy

on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
    inputs:
      namespace:
        required: true
        type: string
      id:
        required: true
        type: string

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4
        with:
          version: v3.13.1

      - name: Setup kubectl
        env:
          DEPLOYER_KUBECONFIG: ${{secrets.kubeconfig}}
        run: |
          echo "$DEPLOYER_KUBECONFIG" >> ./kubeconfig

      - name: Uninstall
        run: |
          helm uninstall ${{ inputs.id }} \
            --kubeconfig kubeconfig \
            --wait \
            --ignore-not-found \
            -n ${{ inputs.namespace }}
