name: Pull request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Install
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/kisielk/errcheck@latest
      - name: format
        if: always()
        run: test -z $(gofmt -l ./.. | grep -v vendor)
      - name: vet
        if: always()
        run: go vet ./...
      - name: errcheck
        if: always()
        run: errcheck ./...
      - name: ineffassign
        if: always()
        run: ineffassign ./...
      - name: staticcheck
        if: always()
        run: staticcheck ./...

  test:
    name: Test Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Run tests
        run: "go test ./..."

  test-playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: "./ui/.nvmrc"
      - name: Install dependencies
        run: npm install
        working-directory: ./ui
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./ui
      - name: Run Playwright tests
        run: npm run test:integration
        working-directory: ./ui

  test-playwright-proxied:
    name: Playwright Tests (Proxied Config)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: "./ui/.nvmrc"
      - name: Install dependencies
        run: npm install
        working-directory: ./ui
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./ui
      - name: Run Playwright tests
        run: npm run test:integration:proxied
        working-directory: ./ui

  lint-svelte:
    name: Lint Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./ui
        if: always()

      - name: svelte-check
        run: npm run check -- --fail-on-warnings
        working-directory: ./ui
        if: always()

  lint-helm:
    name: Lint Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
        with:
          version: v3.13.1

      - name: Lint helm
        run: helm lint .
        working-directory: ./helm/ced
