name: Pull request

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Install
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/kisielk/errcheck@latest
          go install github.com/google/go-licenses@latest
      - name: format
        if: always()
        run: test -z $(gofmt -l ./.. | grep -v vendor)
      - name: vet
        if: always()
        run: go vet ./...
      - name: errcheck
        if: always()
        run: errcheck ./...
      - name: ineffassign
        if: always()
        run: ineffassign ./...
      - name: staticcheck
        if: always()
        run: staticcheck ./...
      - name: license
        if: always()
        run: go-licenses check --ignore github.com/bradenrayhorn/ced --confidence_threshold 0.85 ./...

  test:
    name: Test Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Run tests
        run: "go test ./..."

  test-playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: "./server/go.mod"
          cache: false
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: "./ui/.nvmrc"
      - name: Install dependencies
        run: npm install
        working-directory: ./ui
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./ui
      - name: Run Playwright tests
        run: npm run test:integration
        working-directory: ./ui

  lint-svelte:
    name: Lint Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version-file: "./ui/.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./ui
        if: always()

      - name: svelte-check
        run: npm run check -- --fail-on-warnings
        working-directory: ./ui
        if: always()

  lint-helm:
    name: Lint Helm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Setup Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
        with:
          version: v3.13.1

      - name: Lint helm
        run: helm lint .
        working-directory: ./helm/ced
