name: Pull Request Cleanup

on:
  pull_request_target:
    types: [closed]

concurrency:
  # must be same as in preview
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  uninstall:
    uses: ./.github/workflows/_undeploy.yml
    with:
      namespace: "ced-pr-preview"
      id: "ced-preview-${{ github.event.pull_request.number }}"
    secrets:
      kubeconfig: ${{ secrets.PREVIEW_DEPLOYER_KUBECTL }}

  comment-closed:
    needs: uninstall
    uses: ./.github/workflows/_comment.yml
    permissions:
      pull-requests: write
    with:
      comment: ""
      searchKey: "site"
      issueNumber: ${{ github.event.pull_request.number }}

