name: Release

on:
  release:
    types:
      - published

jobs:
  docker:
    name: Retag and push images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2

      - name: Tag and push ui
        run: |
          IMAGE=ghcr.io/bradenrayhorn/ced-ui
          EXISTING_TAG=$IMAGE:next-${{ github.sha }}
          TAG=${{ github.event.release.tag_name }}
          RELEASE_VERSION="${TAG//v/}"

          docker buildx imagetools create \
            --tag $IMAGE:$RELEASE_VERSION \
            --tag $IMAGE:latest \
            $EXISTING_TAG

      - name: Tag and push server
        run: |
          IMAGE=ghcr.io/bradenrayhorn/ced-server
          EXISTING_TAG=$IMAGE:next-${{ github.sha }}
          TAG=${{ github.event.release.tag_name }}
          RELEASE_VERSION="${TAG//v/}"

          docker buildx imagetools create \
            --tag $IMAGE:$RELEASE_VERSION \
            --tag $IMAGE:latest \
            $EXISTING_TAG

