name: Relase Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  release:
    name: Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'

      - name: Package and release
        working-directory: ./helm/ced
        run: |
          VERSION=$(helm show chart . | yq '.version')
          PACKAGE=ced-helm-$VERSION.tgz

          helm package .

          echo ${{secrets.GITHUB_TOKEN}} | helm registry login ghcr.io/bradenrayhorn --username ${{github.actor}} --password-stdin

          helm push ./$PACKAGE oci://ghcr.io/bradenrayhorn

